export const cars = {
  en: {
    bugatti: {
      title: 'Bugatti Type 57SC Atlantic',
      image: 'img/bugatti_img.png',
      manufacturer: 'Bugatti Automobiles',
      production: '1934–1940',
      engine: '3257 cc',
      topSpeed: '95 mph',
      txt: 'The Type 57S Atlantic body featured flowing coupé lines with a pronounced dorsal seam running from the front to the back end of the vehicle. It was based on the 1935 Aérolithe concept car designed by Jean Bugatti which was built on a prototype chassis, more specifically, a standard Type 57 chassis shortened to what would eventually become the Type 57S chassis.',
    },
    cadillac: {
      title: 'Cadillac V-16',
      image: 'img/cadillac_img.png',
      manufacturer: 'Cadillac (General Motors)',
      production: '1930–1940',
      engine: '7410 cc',
      topSpeed: '100 mph',
      txt: `The Cadillac V-16 (also known as the Cadillac Sixteen) was Cadillac's top-of-the-line model from its January 1930 launch until 1940. The V16 powered car was a first in the United States, both extremely expensive and exclusive, with every chassis being custom-finished to order. Only 4,076 were constructed in its 11-year run, with the majority built in its debut year before the Great Depression took strong hold. The onset of World War II reduced the sales, resulting in its demise.`,
    },
    ferrari: {
      title: 'Ferrari 250 GTO',
      image: 'img/ferrari_img.png',
      manufacturer: 'Ferrari',
      production: '1962–1964',
      engine: '2953 cc',
      topSpeed: '174 mph',
      txt: `The Ferrari 250 GTO is a GT car produced by Ferrari from 1962 to 1964 for homologation into the FIA's Group 3 Grand Touring Car category. The "250" in its name denotes the displacement in cubic centimeters of each of its cylinders; "GTO" stands for Gran Turismo Omologato, Italian for "Grand Touring Homologated.When new, the 250 GTO cost $18,000 in the United States, with buyers personally approved by Enzo Ferrari and his dealer for North America, Luigi Chinetti.`,
    },
    jaguar: {
      title: 'Jaguar E-Type',
      image: 'img/jaguar_img.png',
      manufacturer: 'Jaguar Cars',
      production: '1961—1974',
      engine: '3781 cc',
      topSpeed: '150 mph',
      txt: `The Jaguar E-Type, or the Jaguar XK-E for the North American market, is a British sports car that was manufactured by Jaguar Cars Ltd between 1961 and 1974. Its combination of beauty, high performance, and competitive pricing established the model as an icon of the motoring world.`,
    },
    mercedes: {
      title: 'Mercedes-Benz 300SL',
      image: 'img/mercedes_img.png',
      manufacturer: 'Mercedes-Benz',
      production: '1955—1963',
      engine: '2996 cc',
      topSpeed: '163 mph',
      txt: `The Mercedes-Benz 300 SL (chassis code W 198) is a two-seat sports car which was produced by Mercedes-Benz as a gullwinged coupe (1954–1957) and roadster (1957–1963). It was based on the company's 1952 racer, the W194, with mechanical direct fuel injection which boosted power almost 50 percent in its three-liter overhead camshaft straight-six engine. Capable of reaching a top speed of up to 263 km/h (163 mph), it was a sports car racing champion and the fastest production car of its time.`,
    },
  },
  ua: {
    bugatti: {
      title: 'Bugatti Type 57SC Atlantic',
      image: 'img/bugatti_img.png',
      manufacturer: 'Bugatti Automobiles',
      production: '1934–1940',
      engine: '3257 см3',
      topSpeed: '192 км/ч',
      txt: `Існує думка, що Atlantic є першим суперкаром. Усього було випущено 3 машини Bugatti Type 57SC Atlantic. Ця модифікація Type 57S (або Type 57SC) була заснована на концепт-карі Aerolithe 1935 року, показаному на Паризькому автосалоні. Розробкою Atlantic займався особисто Жан Бугатті. Кузов був зроблений зі сплаву, який був дуже легким та водночас вогненебезпечним, що не дозволяло з'єднувати деталі автомобіля методом зварювання. Деталі кріпилися клепками, які, за ідеєю Жана Бугатті, вивели назовні.`,
    },
    cadillac: {
      title: 'Cadillac V-16',
      image: 'img/cadillac_img.png',
      manufacturer: 'Cadillac (General Motors)',
      production: '1930–1940',
      engine: '7410 см3',
      topSpeed: '160 км/ч',
      txt: `Cadillac V16 (Cadillac Sixteen) виготовляла американська компанія Cadillac з січня 1930 до падіння продажів через початок війни (1940). Це був перший у світі серійний автомобіль люкс-класу з 16-циліндровим мотором. В залежності від модифікації автомашини коштували 4495–9700 доларів. Сьогодні на аукціонах вартість авто становить близько 500.000 доларів.`,
    },
    ferrari: {
      title: 'Ferrari 250 GTO',
      image: 'img/ferrari_img.png',
      manufacturer: 'Ferrari',
      production: '1962–1964',
      engine: '2953 см3',
      topSpeed: '280 км/ч',
      txt: `Автомобіль класу суперкар, який виробляла компанія Ferrari з 1962 по 1964 рік для участі в гонках ФІА категорії GT3. Перша частина назви позначає об'єм кожного циліндра в кубічних сантиметрах, а друга частина - абревіатура від "Gran Turismo Omologata", що в перекладі з італійської означає "Автомобіль, допущений до перегонів". Новий GTO коштував 18 000 доларів (у США), і покупця повинен був схвалити особисто Енцо Феррарі та його представник у Північній Америці, Луїджі Чинетті.`,
    },
    jaguar: {
      title: 'Jaguar E-Type',
      image: 'img/jaguar_img.png',
      manufacturer: 'Jaguar Cars',
      production: '1961—1974',
      engine: '3781 см3',
      topSpeed: '250 км/ч',
      txt: `Спортивний автомобіль англійської фірми Jaguar, що випускався в період із 1961 по 1974 рік. Поєднував у собі оригінальний зовнішній вигляд, високу швидкість, гарні ходові властивості та був відносно недорогим. Вважається одним із найкрасивіших і стильних автомобілів у світі.`,
    },
    mercedes: {
      title: 'Mercedes-Benz 300SL',
      image: 'img/mercedes_img.png',
      manufacturer: 'Mercedes-Benz',
      production: '1955—1963',
      engine: '2996 см3',
      topSpeed: '240 км/ч',
      txt: `Перший спортивний автомобіль західнонімецької торгової марки Mercedes-Benz післявоєнного періоду. Модель вперше була представлена на Нью-Йоркському автосалоні в 1954 як вулична версія гоночного автомобіля W194.`,
    },
  },
};
